#!/bin/sh
# Regenerate db/schema.sql -- the whole schema in one file, for reading and
# reviewing. Migrations remain the source of truth; this is derived.
#
# dbmate can write this itself, but it shells out to `pg_dump` on the host and
# this repo needs no host Postgres client. The compose `postgres` service has a
# `pg_dump` of exactly the server's version (which matters -- pg_dump refuses to
# dump a server newer than itself), so it is used instead.
#
# Schema only, no owners or grants: those differ per environment and would make
# the file churn for reasons that are not schema changes. `schema_migrations`
# rows ARE included, so the file records which migrations it represents.
set -e

cd "$(dirname "$0")/.."

SERVICE=postgres
USER_NAME=solpg
DB_NAME=solpg
OUT=db/schema.sql

if ! docker compose -f ../compose.yaml ps "$SERVICE" 2>/dev/null | grep -q "Up"; then
  echo "The '$SERVICE' service is not running." >&2
  echo "Start it with: docker compose --profile v2 up -d $SERVICE" >&2
  exit 1
fi

{
  echo "-- Generated by \`yarn db-dump\`. Do not edit."
  echo "--"
  echo "-- Derived from db/migrations/, which is the source of truth. Regenerate"
  echo "-- after adding or editing a migration; never hand-edit this file."
  echo

  docker compose -f ../compose.yaml exec -T "$SERVICE" \
    pg_dump --username "$USER_NAME" --dbname "$DB_NAME" \
    --schema-only --no-owner --no-privileges --no-comments

  echo "--"
  echo "-- Applied migrations"
  echo "--"
  docker compose -f ../compose.yaml exec -T "$SERVICE" \
    pg_dump --username "$USER_NAME" --dbname "$DB_NAME" \
    --data-only --table=schema_migrations --no-owner --no-privileges
} > "$OUT"

echo "Wrote $OUT"
