service: playground-server
runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

# Environment variables
env_variables:
  PG_DB_URI: $PG_DB_URI

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 20

beta_settings:
  cloud_sql_instances: "analytics-324114:us-central1:solpg"