name: CICD Server

on:
  push:
    branches:
      - v0.29
    tags:
      - 'v0.29.*'

jobs:
  format_server:
    name: Format server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --check

  clippy_server:
    name: Clippy server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - name: Add clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

  deploy:
    name: Deploy Playground Server
    runs-on: ubuntu-latest
    needs:
      - format_server
      - clippy_server
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v0.29
          fetch-depth: 0

      - name: Set up Git to get tag and normalize for App Engine
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Raw tag: $TAG"
          NORMALIZED_TAG="${TAG//./-}"
          echo "Normalized tag: $NORMALIZED_TAG"
          echo "VERSION_TAG=$NORMALIZED_TAG" >> $GITHUB_ENV

      - name: Set up Cloud SDK authentication
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure GCloud
        run: |-
          gcloud config set account ${{ secrets.SERVICE_ACCOUNT }}
          gcloud config set project ${{ secrets.PROJECT_ID }}

#      - name: Replace app.yaml environment variables
#        uses: 73h/gae-app-yaml-replace-env-variables@v0.1
#        env:
#          PG_DB_URI: ${{ secrets.PROD_DB_URI }}
#        with:
#          app_yaml_path: app.yaml

      - name: Deploy to App Engine with specific version (no promote)
        uses: google-github-actions/deploy-appengine@v2
        env:
          CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1800  # 30 minutes
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: app.yaml
          version: ${{ env.VERSION_TAG }}
          promote: false
          working_directory: server